package com.pamoja.app.data.remote.auth

import android.app.Activity
import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.crashlytics.FirebaseCrashlytics
import com.pamoja.app.R
import com.pamoja.app.domain.error.AppError
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CancellationException
import javax.inject.Inject

/**
 * Fetches a Google ID token through Credential Manager.
 *
 * Kept out of the repository because obtaining the token needs an Activity to
 * host the account sheet, which the data layer has no business holding. The
 * repository takes the finished token instead.
 *
 * The server client ID is `default_web_client_id`, generated by the
 * google-services plugin from the `client_type: 3` entry in
 * google-services.json. If that file has no web client the resource will not
 * exist and this will not compile, which is the correct failure: Google
 * sign-in genuinely cannot work without it.
 */
class GoogleCredentialClient @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    /** Raised when the user dismissed the sheet. Not an error worth showing. */
    class Cancelled : Exception("Google sign in was cancelled")

    /**
     * Not `runCatching`. That swallows [CancellationException], which turns a
     * coroutine cancelled by ordinary navigation into a sign-in failure the
     * user then sees an error card about.
     */
    private inline fun <T> credentialCatching(block: () -> T): Result<T> = try {
        Result.success(block())
    } catch (e: CancellationException) {
        throw e
    } catch (e: Throwable) {
        Result.failure(e)
    }

    suspend fun getIdToken(activity: Activity): Result<String> = credentialCatching {
        // This method is called by Pamoja's visible "Continue with Google"
        // button, so it must use Google's button flow. GetGoogleIdOption is for
        // the passive Credential Manager bottom sheet and can return
        // NoCredentialException even when accounts exist but need
        // reauthentication or sign-in prompts are disabled.
        val option = GetSignInWithGoogleOption.Builder(
            serverClientId = context.getString(R.string.default_web_client_id),
        )
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()

        val response = try {
            CredentialManager.create(context).getCredential(activity, request)
        } catch (e: GetCredentialCancellationException) {
            throw Cancelled()
        } catch (e: NoCredentialException) {
            // This does not prove that the phone has no Google account. It can
            // also mean Play services or the provider could not open the
            // account flow, so never tell a multi-account user to add one.
            FirebaseCrashlytics.getInstance().recordException(e)
            throw AppError.ProviderUnavailable(
                detail = "Google credential provider returned no credential",
                cause = e,
            )
        } catch (e: GetCredentialException) {
            // Everything else here is a configuration or Play Services problem
            // that the user cannot act on and we cannot diagnose from the
            // generic card they see. Record the real type so the next failure
            // is answerable without a logcat capture.
            FirebaseCrashlytics.getInstance().recordException(e)
            throw e
        }

        val credential = response.credential
        if (credential !is CustomCredential ||
            credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            error("Unexpected credential type from Google")
        }

        GoogleIdTokenCredential.createFrom(credential.data).idToken
    }
}
