package com.pamoja.app.data.remote.auth

import android.app.Activity
import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.pamoja.app.R
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject

/**
 * Fetches a Google ID token through Credential Manager.
 *
 * Kept out of the repository because obtaining the token needs an Activity to
 * host the account sheet, which the data layer has no business holding. The
 * repository takes the finished token instead.
 *
 * The server client ID is `default_web_client_id`, generated by the
 * google-services plugin from the `client_type: 3` entry in
 * google-services.json. If that file has no web client the resource will not
 * exist and this will not compile, which is the correct failure: Google
 * sign-in genuinely cannot work without it.
 */
class GoogleCredentialClient @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    /** Raised when the user dismissed the sheet. Not an error worth showing. */
    class Cancelled : Exception("Google sign in was cancelled")

    suspend fun getIdToken(activity: Activity): Result<String> = runCatching {
        val option = GetGoogleIdOption.Builder()
            .setServerClientId(context.getString(R.string.default_web_client_id))
            // False so every Google account on the device is offered, not only
            // ones that have used Pamoja before. This is a first sign-in gate,
            // so filtering to authorized accounts would show an empty sheet.
            .setFilterByAuthorizedAccounts(false)
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()

        val response = try {
            CredentialManager.create(context).getCredential(activity, request)
        } catch (e: GetCredentialCancellationException) {
            throw Cancelled()
        } catch (e: NoCredentialException) {
            throw Exception("No Google account on this phone. Add one in Settings, or use phone or email instead.")
        }

        val credential = response.credential
        if (credential !is CustomCredential ||
            credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            error("Unexpected credential type from Google")
        }

        GoogleIdTokenCredential.createFrom(credential.data).idToken
    }
}
